--- 
- 
  hosts: jeff_pis
  become: true
  become_method: sudo
  become_user: root
  tasks:
  
      - name: Ensure pip3 is installed 
      apt:
        name: python3-pip 
        state: present


    - name: Ensure setuptools is installed 
      apt:
        name: python3-setuptools
        state: present

    - name: Install pyserial with pip
      pip:
        name: pyserial


    - name: Install Pillow with pip
      pip:
        name: Pillow

    -  name: Get gonet3 repo from GitHub
       git: 
        dest: /home/pi/Tools/git_repo
        repo: "https://github.com/Wied58/gonet3.git"
        update: yes
        force: yes

    - name: Change owership and permissions
      file:
        path: /home/pi/Tools/git_repo
        state: directory
        owner: pi 
        group: pi
        # when specifying mode using octal numbers, add a leading 0
        mode: 0755
        recurse: yes
        
        
